controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

batch:
    path: /api/batch
    controller: ApiPlatform\Core\Action\PlaceholderAction
    methods: POST